### ISSUE TITLE
RuntimeException in EncryptionServiceProvider.php 

### ISSUE THREAD

**Issue by atefBB** [nexmo-community/laravel-sms#1]
Hey there, when I try to log to "http://localhost:8000/sms/send/MY_NUMBER" I got this error : 
«RuntimeException in EncryptionServiceProvider.php line 45:
No supported encrypter found. The cipher and / or key length are invalid.»
Any ideas to solve this prob?
thanks.

**Comment by leggetter** [comment]
This SO question looks relevant:
http://stackoverflow.com/questions/31512970/laravel-no-supported-encrypter-found-the-cipher-and-or-key-length-are-invalid

My guess right now would be that you should run:

``` sh
php artisan key:generate
```

Please let me know if this fixes things and I'll update the README.

**Comment by atefBB** [comment]
Thaaaaaaaaaaaaaaaaaaanks, it's work now.
